Optimize Week 5 Erect Stage
FunkinCrew/funkin.assets pull request #59
Opened 2024-09-17 03:31 UTC by AbnormalPoof

We shouldn't have to make a new `AdjustColorShader` instance *every frame*!

2024-09-17 06:31 UTC, AppleHair approved these changes

2024-09-17 14:32 UTC, NotHyper-474 approved these changes

2024-09-17 23:55 UTC, CyndaquilDAC approved these changes

2024-09-18 00:13 UTC, charlesisfeline approved these changes

2024-09-18 12:04 UTC, kawuchuu approved these changes

2024-09-18 19:34 UTC, CrusherNotDrip approved these changes

2024-09-19 05:53 UTC, bananaTiko approved these changes

2024-09-19 13:18 UTC, BombasticTom approved these changes
either way i approve

2024-09-21 00:23 UTC, Raltyro requested changes
Instead of doing stuff in onUpdate, why not just do it on overriding refresh callback?
then you don't need the null check anymore

2024-09-21 00:25 UTC, AbnormalPoof commented
That might be a bit out of scope for this PR, I don't want to modify the original stage script *too much*. I simply moved the `AdjustColorShader` to `buildStage` instead of `onUpdate`.

2024-09-21 00:32 UTC, Raltyro commented
thats fair...

2024-09-21 00:32 UTC, Raltyro approved these changes

2024-09-22 23:35 UTC, JVNpixels approved these changes

2024-09-24 02:09 UTC, AbnormalPoof commented
Just looked at [FunkinCrew/Funkin#3161](https://github.com/FunkinCrew/Funkin/issues/3161), seems as if it was fixed internally!

2024-09-24 02:09 UTC, closed without merging

2024-09-24 02:14 UTC, Raltyro commented
its so good that the team isnt checking this repo pull requests 😭