Fix alpha, color transform in adjustColor shader
FunkinCrew/funkin.assets pull request #65
Opened 2024-09-30 19:18 UTC by inky03

the adjustColor fragment shader multiplies the color by alpha on the output.  the color is already premultiplied by alpha, so this only causes colors to turn darker as the opacity / alpha decreases, causing black edges and making the output look "dirty". this is specially noticeable in glows and particles!!
**BEFORE:**
![image](https://github.com/user-attachments/assets/ba5f9a04-6178-4f54-9a7d-6538132bd33d)
this tiny fix simply removes that alpha multiplication, essentially fixing this issue
**AFTER:**
![image](https://github.com/user-attachments/assets/9cb322fb-590a-4cd6-a870-0374e12bd8c5)

`texture2D` has also been changed to `flixel_texture2D`, to allow Flixel color and alpha transformations to be applied (pictured below). this doesn't affect the appearance of sprites without these transformations applied
![image](https://github.com/user-attachments/assets/fc4c763d-4ee2-4dd6-a5a7-562e46184bb7)

2024-09-30 19:34 UTC, AppleHair approved these changes

2024-09-30 21:21 UTC, MaybeMaru approved these changes

2024-09-30 22:20 UTC, inky03 commented
OK, really hope this is the last change i have to do...
color and alpha transform is now applied AFTER applying the hsbc effect. This should fix some previous issues with alpha transform and should make it consistent with flash / animate behavior. it also generally makes more sense for it to be applied like this, compared to how it previously did (pictured below)
![image](https://github.com/user-attachments/assets/2c01d6b5-b122-4d88-8f30-155337b8dcc3)

**BEFORE:** (both images have the right hand character colored to RED `ff0000`)
![image](https://github.com/user-attachments/assets/83433c94-0a70-49fe-a06c-ea1989f038d4)
**AFTER:**
![image](https://github.com/user-attachments/assets/60c48b89-2ba3-46b6-8779-7f003fa6a093)
i'll be happy to answer any further questions!!

2024-10-01 06:07 UTC, AppleHair approved these changes

2024-10-03 21:20 UTC, MaybeMaru approved these changes

2025-08-11 19:59 UTC, AbnormalPoof requested changes
Please resolve the merge conflicts on this PR within 90 days.

2026-03-12 15:42 UTC, EliteMasterEric commented
The PR is stale, and the associated shader has been heavily modified since this PR.

2026-03-12 15:42 UTC, closed without merging