Improved Character Offsets
FunkinCrew/funkin.assets pull request #79
Opened 2024-10-10 00:25 UTC by CEliuxJV

As I mentioned earlier in an improvement request on the issues tab (FunkinCrew/Funkin/issues/3105) (because I didn't know how to use pull requests), I improved the offsets of most characters. I’m a bit of a perfectionist, and it was uncomfortable to see that many characters didn’t have their offsets set correctly, so I tried to make them pixel-perfect myself.

Here’s an example with BF’s offsets (Video recorded in version 0.4.1):
https://github.com/user-attachments/assets/ec485f32-d182-4da7-8cf2-1b0f4d7e51c1  

I also adjusted the offsets for the animations in the story mode menu for BF and Pico:  
https://github.com/user-attachments/assets/7726c276-60d2-4eca-84c5-151b7f4564a0

I made a few more changes in the sprite `.json` files:  
- I added "hold" animations to the singing animations of BF Car, so that if an arrow key is held down, the hair animation doesn’t freeze.  
- I restored the inverted animations of Monster (as originally created by Phantom Arcade).  
- I added animations that aren’t used but are nice to have implemented, like the "hey" animation of BF Christmas, and the "hey" and "cheer" animations of Pico Dark.  
- Within the `.json` files, I organized several disordered animations to give more coherence across all the `.json` files and make it less confusing to modify things between them.  
- I removed some unnecessary animations, like two animations named "singUP" that were in the GF Pixel and BF Holding GF `.json` files.
- Create a `.json` apart from Tankman with its animations in the direction they appear in the sprite (This is for when the option to correctly rotate the characters horizontally with their animations is added. I will leave it as a separate file in case it can help when the function is implemented)
[tankman.json](https://github.com/user-attachments/files/17320154/tankman.json)

I couldn’t change the pixel characters' offsets because something changed in the pixel style, making their offsets different from the normal characters' offsets. When the animation editor is fixed (since it doesn’t work or I just don't know how to use it in the latest update), I’ll try to make the pixel character offsets pixel-perfect as well.

I also noticed that you’re planning to make the characters' animations and offsets flip horizontally along with the character sprites when selected as either the opponent or the player. For this, I recommend creating a boolean value called "characterPlayableSprite" within the characters' `.json` file, with a default value of `false`. When activated, if the character is placed in the player's spot, the sprite doesn’t flip horizontally, but it does when placed as the opponent. The inverse would happen when the value is `false`—if the character is the opponent, the sprite doesn’t flip, but if they’re the player, it does (this would also affect the left and right singing animations to match their position).

One way to ensure characters don't look strange in different environments (outside of their own) and to make them more compatible with all backgrounds would be to add a reference in the animation editor to show where the characters should be positioned. A reference "X" could be added at position [0, 0], and based on that "X," you could modify the character's general offset to keep it centered relative to the "X" (it would be helpful if there was a way to adjust the character’s offset, not just individual animation offsets).

2024-10-10 00:31 UTC, CEliuxJV commented
I have a few more recommendations related to these things:  
- When I was modifying the story mode offsets, I noticed that each week’s `.json` file sets the animations and offsets for the characters’ assets. To avoid having to do this in every `.json` file for each week, I recommend creating a single `.json` file that contains the animations and offsets for each character. The weekly `.json` files would just use that file to select which characters to include in each week. If it’s not possible to include all characters in a single `.json` file, then make a separate `.json` file for each character, similar to how the characters’ `.json` files are handled within the game.  

- It would also be nice that, once the sprites can be flipped horizontally perfectly, there’s no need to create separate playable variants of characters, like with Pico, who has both an opponent and a player variant.  
- Similarly, in the story mode menu, adjust the scale as necessary to display correctly and flip the sprite horizontally, like with Pico, so there’s no need for different sprites for his playable and opponent versions.

- For characters with several animation sprites (such as BF, GF, Pico, Nene, Tankman, or even Skid and Pump and Senpai), it would be good to create a folder within the "characters" folder for each of them, containing all their animation sprites. This way, the characters folder won’t get cluttered with multiple sprites for different animations of the same character.

- It would also be helpful to combine some sprite sheets at some point to reduce the number, like Pico’s singing and fail animations, or BF’s cheer animation, etc.  
- At the same time, separate certain animations, such as BF’s death animation, so they aren’t on the same sprite sheet as the base BF animations. This way, BF variants don’t have to access the entire original sprite sheet just to display the death animation.

- Please optimize and organize the sprite sheets better. Remove large blank spaces and organize the animations more like this:  
![60cd0ce381cd2](https://github.com/user-attachments/assets/069848ba-6202-4697-8a33-aae65dd91b15)
Source of the image: https://gamebanana.com/mods/296576

P.S. Sorry for including so many recommendations. There are many things I’d like to see improved in the game for better organization (and I’m not good enough at programming to add all of this myself, sorry).

2024-10-10 03:40 UTC, Hundrec commented
Thank you for working on pixel perfect offsets! It's also something I care a great deal about. 

I want to mention that #39 makes adjustments to every character's offsets as well. Does this PR set to do the same thing as the other one?

2024-10-10 05:22 UTC, CEliuxJV commented
> I want to mention that https://github.com/FunkinCrew/funkin.assets/pull/39 makes adjustments to every character's offsets as well. Does this PR set to do the same thing as the other one?

Oh, thanks for letting me know about that PR, I hadn’t seen it. When I started modifying the character offsets a long time ago, I only looked at the PRs for the game’s source code, and I didn’t know that the assets had their own section with their own PRs, so to speak. It was only when I was about to submit the PR that I realized this, and I completely forgot to check if this request had already been made before.

The changes I made in this PR were all related to the animation offsets and organizing the characters’ `.json` files a bit. I didn’t consider their in-game positions because I didn’t have a reference for all of them to align to a common position, like in request #39. That’s why I mentioned that such an implementation would be a good addition here:

I just checked request #39, and it also changes the animation offsets, though it slightly modifies the idle animations too, and I prefer to keep them at [0, 0]. Basically, my PR does the same thing as #39, but without changing the characters' positions so they remain compatible in all stages.

I could try adjusting the offset for each character completely, as well as in each scenario file, so that everything can be 100% compatible.

2025-08-11 19:59 UTC, AbnormalPoof requested changes
Please resolve the merge conflicts on this PR within 90 days.

2025-08-23 07:22 UTC, Hundrec commented
Oh wow, nice job!
Is every change here still relevant? I'm interested in this PR

2025-08-23 07:24 UTC, Hundrec commented
I will note that a good way to get this reviewed would be to create a new branch in your fork for each character's sprites, then PR each character's changes separately.
I'll be here to test!

2025-08-23 07:27 UTC, CEliuxJV commented
Done, all the offsets for all the characters (except those using sprite maps because I don't know how that works) have been updated to be compatible with the latest version of the game.

Tomorrow I'll update the PR and write up all the changes I made, but basically it was just adjusting the animation offsets and other small things.

2025-08-23 07:29 UTC, CEliuxJV commented
Dude, I didn't even finish writing the article ("article" the translator is weird) I was going to post and you were already here reading my PR.

Love you @Hundrec

2025-08-23 07:32 UTC, CEliuxJV commented
> Oh wow, nice job! Is every change here still relevant? I'm interested in this PR

I mean, I guess, Just to perfect the animation offsets of all characters, I can soon do the other thing I wanted, making all the characters compatible in all the scenarios without them looking weird.

2025-08-23 07:34 UTC, Hundrec commented
Happy to help you get offsets fixed for good!
Here's my plan of action for you:

1. Create a new branch in your fork based on the `develop` branch of funkin.assets
2. Migrate one "group" of changes to it (for example, only BF offsets)
3. Open a PR from your branch to `develop` on funkin.assets
4. Repeat steps 1-3 until all of your changes are requested, no matter how many PRs this creates.

If you can systematically PR every change this way, we'll make it to perfection in no time 💯

2025-08-23 07:34 UTC, CEliuxJV commented
> I will note that a good way to get this reviewed would be to create a new branch in your fork for each character's sprites, then PR each character's changes separately.

Thanks for telling me, I barely use GitHub and I don't know many of its functions, I barely know how to program, I'm very new, but I'm quite interested in this, I like to help with these things

2025-08-23 07:38 UTC, CEliuxJV commented
> Happy to help you get offsets fixed for good! Here's my plan of action:
> 
> 1. Create a new branch in your fork based on the `develop` branch of funkin.assets
> 2. Migrate one "group" of changes to it (for example, only BF offsets)
> 3. Open a PR from your branch to `develop` on funkin.assets
> 4. Repeat steps 1-3 until all of your changes are requested, no matter how many PRs this creates.
> 
> If you can systematically PR every change this way, we'll make it to perfection in no time 💯

Ok, I'll try it when I can. Thanks for the tips ❤️

2025-08-23 07:57 UTC, CEliuxJV commented
@Hundrec, do you prefer character .json files to be in the "default" format or the format exported by the animation editor?

I exported all .json files with the editor, and I think the format is a bit odd.

Why is the "default" format different from the one exported by the editor?
Do you have another version of the editor, or do you just code it in manually?

I'm asking in case you need me to change it.

2025-08-23 08:00 UTC, Hundrec commented
It looks to me like the game is exporting json files with more spacing than the json files we currently have
Our current files were likely manually reformatted.
Ideally, the "diff" would be as small as possible. That means going into current json files on the `develop` branch and changing the numbers to match your exported json files.

This is a lot of work, so take your time if you're willing to pursue this!  

Also, you may add me on Discord @hundrec so we can work together more closely

2025-08-23 08:17 UTC, CEliuxJV commented
> That means going into current json files on the `develop` branch and changing the numbers to match your exported json files.
> 
> This is a lot of work, so take your time if you're willing to pursue this!  


Ok, I will do it in the not too distant future, if you don't have a problem with that. I don't think it took me more time than it took me to transfer sprites to Psych Engine, change the offsets in Psych Engine and then change the offsets in the V-Slice editor or in the .json manually (Sorry but the current editor of the game sucks 😭. Please copy the Psych editor, it's the best ever)

> Also, you may add me on Discord @hundrec so we can work together more closely

Love you Hundrec, I'll probably write you tomorrow if I have any questions (my name is the same on all platforms)

2025-08-24 21:37 UTC, CEliuxJV commented
I'm going to close this PR because I divided it into 3 parts

2025-08-24 21:41 UTC, CEliuxJV commented
I don't know how to close it without a comment, oops

2025-08-24 21:41 UTC, closed without merging

2025-08-25 10:17 UTC, Hundrec commented
Thanks, I'll label those PRs accordingly!